---
allow_overwrite: true
root_source_code_dir: ~/source
default_git_email: alec@fatninjas.work
default_git_name: Head Ninja
environment: linux
is_wsl: true
overwrite_workspace: false
dotfiles:
  has_dotfiles: true
  dotfiles_repo: 'git@github.com:wanderinggoose/dotfiles.git'
  bootstrapper_script: 'bootstrap'
  install_script: 'install'
