alias pad="pnpm add -D"
alias pa="pnpm add"
alias pi="pnpm install"
alias pr="pnpm remove"
alias pup="pnpm update"

## Project Operations
alias @pb="pnpm build"
alias @pba="pnpm build:all"
alias @pbsc="pnpm build:no-cache"
alias @plint="pnpm lint"
alias @pd="pnpm dev"
alias @ps="pnpm start"
alias @psv="pnpm serve"
alias @pt="pnpm test"
