## NX ##
alias baa="yarn nx run-many --target=build --all"
alias nxb="yarn nx build"
alias nxba="yarn nx affected --target=build --all=true"
alias nxta="yarn nx run-many --target=test --all"
alias nxt="yarn nx test"
alias nxbta="nxba && nxta"
alias nxaddlib="yarn nx g @nrwl/workspace:lib"
alias nxml="yarn nx migrate latest"
alias nxrm="yarn nx migrate --run-migrations"
