## NX ##
alias nxbaa="npx nx run-many --target=build --all"
alias nxb="npx nx build"
alias nxba="npx nx affected --target=build --parallel=true --maxParallel=8 --all=true --skip-nx-cache=true"
alias nxta="npx nx affected --target=test --parallel=true --maxParallel=8 --all=true --skip-nx-cache=true"
alias nxt="npx nx test"
alias nxbta="nxba && nxta"
alias nxaddlib="npx nx g @nrwl/workspace:lib"
alias nxml="npx nx migrate latest"
alias nxrm="npx nx migrate --run-migrations"
